#!/usr/bin/env python3
"""Build assets/js/home-i18n-data.js from static blocks in home-i18n.js (run after editing messages)."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "assets/js/home-i18n.js"
OUT = ROOT / "assets/js/home-i18n-data.js"

MARKERS = [
    ("CASA_FUEGO_GEOS", "  var CASA_FUEGO_GEOS = "),
    ("CORESYNC_GEOS", "  var CORESYNC_GEOS = "),
    ("EN_HOME_MARKETS", "  var EN_HOME_MARKETS = "),
    ("LOCALE_LABELS", "  var LOCALE_LABELS = "),
    ("HTML_LANG", "  var HTML_LANG = "),
    ("PRODUCT_PRICES", "  var PRODUCT_PRICES = "),
    ("PRICED_LINES", "  var PRICED_LINES = "),
    ("MESSAGES", "  var MESSAGES = "),
]


def extract_value(text: str, start_marker: str) -> str:
    idx = text.index(start_marker) + len(start_marker)
    depth = 0
    i = idx
    started = False
    while i < len(text):
        ch = text[i]
        if ch in "{[":
            depth += 1
            started = True
        elif ch in "}]":
            depth -= 1
            if started and depth == 0:
                return text[idx : i + 1]
        i += 1
    raise ValueError(f"Could not extract value for {start_marker}")


def main() -> None:
    text = SRC.read_text(encoding="utf-8")
    parts = []
    for name, marker in MARKERS:
        val = extract_value(text, marker)
        parts.append(f"  {name}: {val}")
    body = ",\n".join(parts)
    out = f"""/* Auto-generated by scripts/make_home_i18n_data.py — do not edit by hand. */
(function (root) {{
  root.HOME_I18N_DATA = {{
{body}
  }};
}})(typeof globalThis !== 'undefined' ? globalThis : window);
"""
    OUT.write_text(out, encoding="utf-8", newline="\n")
    print("Wrote", OUT.relative_to(ROOT))


if __name__ == "__main__":
    main()
